import {GlobalProvider} from './GlobalProvider'
import Footer from './component/footer/Footer'
import Head from './component/header/Head'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NEXTBAZAR',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <GlobalProvider>
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  )
}
